name: Plugin release

on:
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: npm build
              run: |
                  npm install
                  npm run build --if-present
            - name: Create Release
              # https://github.com/ncipollo/release-action
              uses: ncipollo/release-action@v1.14.0
              with:
                  artifacts: "main.js,manifest.json,styles.css"
                  token: ${{ secrets.GITHUB_TOKEN }}